apiVersion: v1
kind: ReplicationController
metadata:
  name: app-frontend
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
